---
included:
  - Sources
only_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
#  - anonymous_argument_in_multiline_closure # 29 violations
  - anyobject_protocol
  - array_init
#  - attributes # 38 violations
  - balanced_xctest_lifecycle
#  - blanket_disable_command # 6 violations
  - block_based_kvo
  - capture_variable
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
#  - closure_parameter_position # 1 violations
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comma_inheritance
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - direct_return
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_direct_init
#  - discouraged_none_name # 1 violations
  - discouraged_object_literal
  - discouraged_optional_boolean
#  - discouraged_optional_collection # 6 violations
  - duplicate_conditions
  - duplicate_enum_cases
  - duplicate_imports
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure # 1 violations (fixable)
  - empty_string
#  - empty_xctest_method # 1 violations
  - enum_case_associated_values_count
  - expiring_todo
#  - explicit_acl # 311 violations
  - explicit_enum_raw_value
  - explicit_init
  - explicit_self
#  - explicit_top_level_acl # 45 violations
#  - explicit_type_interface # 546 violations
  - extension_access_modifier
  - fallthrough
#  - fatal_error_message # 4 violations
  - file_header
#  - file_length # 1 violations
#  - file_name # 42 violations
  - file_name_no_space
#  - file_types_order # 82 violations
  - final_test_case # 17 violations (fixable)
  - first_where
  - flatmap_over_map_reduce
#  - for_where # 1 violations
#  - force_cast # 9 violations
#  - force_try # 43 violations
#  - force_unwrapping # 76 violations
  - function_body_length
#  - function_default_parameter_at_end # 4 violations
  - function_parameter_count
  - generic_type_name
  - ibinspectable_in_extension
  - identical_operands
#  - identifier_name # 206 violations
  - implicit_getter
  - implicit_return
#  - implicitly_unwrapped_optional # 9 violations
  - inclusive_language
#  - indentation_width # 14 violations
  - inert_defer
  - invalid_swiftlint_command
#  - is_disjoint # 1 violations
  - joined_default_parameter
#  - large_tuple # 6 violations
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
#  - legacy_multiple # 1 violations
  - legacy_nsgeometry_functions
#  - legacy_objc_type # 20 violations
  - legacy_random
#  - let_var_whitespace # 20 violations
#  - line_length # 204 violations
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - mark # 13 violations (fixable)
#  - missing_docs # 572 violations
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
#  - nesting # 4 violations
  - nimble_operator
#  - no_extension_access_modifier # 171 violations
  - no_fallthrough_only
#  - no_grouping_extension # 61 violations
#  - no_magic_numbers # 577 violations
  - no_space_in_method_call
#  - non_optional_string_data_conversion # 3 violations
  - non_overridable_class_declaration
  - notification_center_detachment
  - ns_number_init_as_function_reference
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - number_separator
  - object_literal
#  - one_declaration_per_file # 59 violations
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - optional_enum_case_matching
#  - orphaned_doc_comment # 15 violations
  - overridden_super_call
  - override_in_extension
#  - pattern_matching_keywords # 14 violations
  - period_spacing
#  - prefer_nimble # 235 violations
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
#  - prefixed_toplevel_constant # 16 violations
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_subject
  - private_swiftui_state
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_self_in_closure
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
#  - required_deinit # 37 violations
  - required_enum_case
  - return_arrow_whitespace
  - return_value_from_void_function
  - self_binding
  - self_in_property_initialization
  - shorthand_argument
  - shorthand_operator
  - shorthand_optional_binding
  - single_test_class
#  - sorted_enum_cases # 127 violations
  - sorted_first_last
  - sorted_imports
  - statement_position # 2 violations (fixable)
#  - static_operator # 1 violations
  - static_over_final_class
  - strict_fileprivate
  - strong_iboutlet
#  - superfluous_disable_command # 6 violations
  - superfluous_else
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - test_case_accessibility # 1 violations (fixable)
#  - todo # 43 violations
  - toggle_bool
  - trailing_closure # 3 violations (fixable)
  - trailing_comma # 9 violations (fixable)
  - trailing_newline # 1 violations (fixable)
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
#  - type_contents_order # 122 violations
#  - type_name # 1 violations
  - typesafe_array_init
  - unavailable_condition
#  - unavailable_function # 1 violations
  - unhandled_throwing_task
  - unneeded_break_in_switch
  - unneeded_override # 2 violations (fixable)
  - unneeded_parentheses_in_closure_argument
  - unneeded_synthesized_initializer
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
#  - unused_enumerated # 1 violations
  - unused_import
  - unused_optional_binding
#  - unused_setter_value # 1 violations
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces # 1 violations (fixable)
  - vertical_whitespace_opening_braces
  - void_function_in_ternary
  - void_return
  - weak_delegate
#  - xct_specific_matcher # 75 violations
  - xctfail_message
  - yoda_condition
