name: Swift
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-15
    env:
      XCODE_VERSION: "16.2"
    steps:
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: swift build -v
      - run: swift test -v

  swiftlint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: brew install swiftlint
      - run: swiftlint --strict

